#!/bin/bash

cat << EOF

************************************************
* STARTUP DAFNY VSCODE DEVELOPMENT ENVIRONMENT *
************************************************

Installing server ...

EOF

cd server
npm install
code .

cat << EOF

Installing client ...

EOF

cd ../client
npm install
code .

cat << EOF

DONE!

EOF