// Generated by typings
// Source: https://raw.githubusercontent.com/mxl/typed-base64/a0090d62f02663621aa2979e0d32fcabc5db1ef9/index.d.ts
declare module 'base64-js' {
namespace Base64Js {
    function toByteArray(b64: string):Uint8Array;

    function fromByteArray(uint8: Uint8Array):string;
}

export = Base64Js
}
